export const GetMenuItems = 'menuitems'
export const GetMenuItemById = 'menuitembyid'
export const GetCategoryItems = 'categoryitems'
export const GetKioskoCategoryItems = 'kioskocategoryitems'
export const GetKioskoItems = 'kioskoitems'
export const GetOrders = 'orders'
export const GetOrdersLastId = 'orderslastid'